project_week/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('yahtzee_app.urls')),
]

yahtzee_app/urls.py
from django.urls import path
from . import views

app_name = 'yahtzee_app'

urlpatterns = [
    path('', views.index),
    path('login', views.login),
    path('login/process', views.login_process),
    path('register', views.register),
    path('register/process', views.register_process),
    path('lobby', views.lobby),
    path('lobby_process', views.lobby_process),
    path('game', views.game),
    path('game_process/<int:num>', views.game_process),
    path('probability', views.probability, name="probability"),
    path('probability/plot', views.img_plot, name="img_plot"),
    path('log_out', views.log_out),

    path('benis',views.benis)
]

yahtzee_app/models.py
from __future__ import unicode_literals
from django.db import models
import re


class AccountManager(models.Manager):
    def basic_validator(self, postData):
        errors = {}
        if len(postData['r_first_name']) < 2:
            errors["first_name"] = "First Name should be at least 2 characters"
        if len(postData['r_last_name']) < 2:
            errors["last_name"] = "Last Name should be at least 2 characters"
        EMAIL_REGEX = re.compile(
            r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['r_email']):
            errors['r_email'] = "Invalid email address!"
        if len(postData['r_password']) < 8:
            errors["password"] = "Password should be at least 8 characters"
        if postData['r_password'] != postData['r_cpassword']:
            errors["password"] = "Passwords do not match!"

        return errors

    def another_validator(self, postData):
        errors = {}
        curr = Account.objects.filter(email=postData['email'])
        EMAIL_REGEX = re.compile(
            r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['email']):
            errors['r_email'] = "Invalid email address!"
        elif len(curr) < 1:
            errors["email"] = "Incorrect email or password"
        elif postData['password'] != curr[0].password:
            errors["password"] = "Incorrect email or password"
        return errors


class Account(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    waiting_for_game = models.BooleanField(null=True)
    game_id = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = AccountManager()

class Score(models.Model):
    scored_user=models.ForeignKey(Account,related_name='past_scores' ,on_delete=models.CASCADE)
    Score=models.IntegerField(verbose_name='score')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

# class Game(models.Model):
#     players = models.ForeignKey(Account,related_name='game_id',on_delete=models.CASCADE)
    
    

yahtzee_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from random import randint
from .models import Account
from django.contrib import messages
import io
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import random
import numpy as np
plt.switch_backend('Agg')

def index(request):
    if 'current_user' not in request.session:
        request.session['current_user'] = 0
    if request.session['current_user'] != 0:
        return redirect('/lobby')
    return redirect('/login')


def login(request):
    if request.session['current_user'] != 0:
        return redirect('/lobby')
    return render(request, 'login.html')


def register(request):
    if request.session['current_user'] != 0:
        return redirect('/lobby')
    return render(request, 'register.html')


def login_process(request):
    errors = Account.objects.another_validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/login')
    else:
        curr = Account.objects.filter(email=request.POST['email'])
        request.session['current_user'] = curr[0].id
        return redirect('/lobby')


def register_process(request):
    errors = Account.objects.basic_validator(request.POST)
    if len(errors) > 0:
        for key, value in errors.items():
            messages.error(request, value)
        return redirect('/register')
    # password = request.POST['r_password']
    # pw_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
    Account.objects.create(first_name=request.POST['r_first_name'], last_name=request.POST['r_last_name'],
                           email=request.POST['r_email'], password=request.POST['r_password'])
    current = Account.objects.filter(email=request.POST['r_email'])
    request.session['current_user'] = current[0].id
    user = request.session['current_user']
    curr = Account.objects.get(id=user)
    curr.game_id = '0'
    curr.save()
    return redirect('/lobby')


def lobby(request):
    if request.session['current_user'] == 0:
        return redirect('/')
    user = request.session['current_user']
    curr = Account.objects.get(id=user)
    curr.waiting_for_game = True
    curr.save()
    if curr.game_id != '0':
        return redirect('/game')
    users = Account.objects.all()
    users2 = users.exclude(id=user)
    none = True
    for i in users2:
        if i.waiting_for_game == True:
            none = False
    context = {
        'users': users2,
        'waiting': users2.all(),
        'noneq': none,
    }
    return render(request, 'lobby.html',context)

def lobby_process(request):
    user = request.session['current_user']
    curr = Account.objects.get(id=user)
    curr.game_id = '0'
    curr.save()
    return redirect('/lobby')

def game(request):
    if request.session['current_user'] == 0:
        return redirect('/')
    user = request.session['current_user']
    curr = Account.objects.get(id=user)
    curr.waiting_for_game = False
    curr.save()
    ran_list = [randint(1, 6), randint(1, 6), randint(
        1, 6), randint(1, 6), randint(1, 6)]
    number_of_1 = 0
    number_of_2 = 0
    number_of_3 = 0
    number_of_4 = 0
    number_of_5 = 0
    number_of_6 = 0
    list2 = []
    total = 0
    pair = 0
    triple = 0
    num = 0

    for i in range(5):
        if ran_list[i] == 1:
            number_of_1 += 1
        if ran_list[i] == 2:
            number_of_2 += 1
        if ran_list[i] == 3:
            number_of_3 += 1
        if ran_list[i] == 4:
            number_of_4 += 1
        if ran_list[i] == 5:
            number_of_5 += 1
        if ran_list[i] == 6:
            number_of_6 += 1
    
    if number_of_1 == 2:
        total += number_of_1*1
        pair += 1
    if number_of_1 == 3:
        triple = 1
        total += number_of_1*1
    if number_of_1 == 4:
        total += number_of_1*1
    if number_of_1 == 5:
        total = 30

    if number_of_2 == 2:
        total += number_of_2*2
        pair += 1
    if number_of_2 == 3:
        triple = 1
        total += number_of_2*2
    if number_of_2 == 4:
        total += number_of_2*2
    if number_of_2 == 5:
        total = 30

    if number_of_3 == 2:
        total += number_of_3*3
        pair += 1
    if number_of_3 == 3:
        triple = 1
        total += number_of_3*3
    if number_of_3 == 4:
        total += number_of_3*3
    if number_of_3 == 5:
        total = 30

    if number_of_4 == 2:
        total += number_of_4*4
        pair += 1
    if number_of_4 == 3:
        triple = 1
        total += number_of_4*4
    if number_of_4 == 4:
        total += number_of_4*4
    if number_of_4 == 5:
        total = 30

    if number_of_5 == 2:
        total += number_of_5*5
        pair += 1
    if number_of_5 == 3:
        triple = 1
        total += number_of_5*5
    if number_of_5 == 4:
        total += number_of_5*5
    if number_of_5 == 5:
        total = 30

    if number_of_6 == 2:
        total += number_of_6*6
        pair += 1
    if number_of_6 == 3:
        triple = 1
        total += number_of_6*6
    if number_of_6 == 4:
        total += number_of_6*6
    if number_of_6 == 5:
        total = 30

    list2.extend([number_of_1, number_of_2, number_of_3,
                  number_of_4, number_of_5, number_of_6])
    if pair == 1 and triple == 1:
        num = 1
        pair = 0
        triple = 0

    context = {
        "num1": f"/static/imgs/dice{ran_list[0]}.png",
        "num2": f"/static/imgs/dice{ran_list[1]}.png",
        "num3": f"/static/imgs/dice{ran_list[2]}.png",
        "num4": f"/static/imgs/dice{ran_list[3]}.png",
        "num5": f"/static/imgs/dice{ran_list[4]}.png",
        "score": list2,
        "total": total,
        "full": num,
        "triple": triple,
        "pair": pair,
    }
    return render(request, 'game.html', context)

def game_process(request, num):
    user = request.session['current_user']
    curr = Account.objects.get(id=user)
    curr2 = Account.objects.get(id=num)
    print(curr.first_name)
    print(curr2.first_name)
    game = randint(0,999999999)
    print(game)
    curr.game_id = game
    curr2.game_id = game
    curr.waiting_for_game = False
    curr2.waiting_for_game = False
    curr.save()
    curr2.save()
    return redirect('/game')

def probability(request):
    if request.session['current_user'] == 0:
        return redirect('/')
    user = request.session['current_user']
    curr = Account.objects.get(id=user)
    curr.waiting_for_game = False
    curr.save()
    if curr.game_id != '0':
        return redirect('/game')
    arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    return render(request, 'probability.html', {'arr': arr,'user':curr})


def plt2png():
    buf = io.BytesIO()
    
    plt.savefig(buf, format='png', dpi=80)
    s = buf.getvalue()
    buf.close()
    return s


def img_plot(request):
    n = 100
    x = [i for i in range(n)]
    y = [random.randint(1, 100) for a in range(n)]
    request.session['max'] = max(y)
    request.session['ave'] = sum(y)/n
    plt.plot(x,y,color=cm.hsv(30.0))
    png = plt2png()
    plt.cla()
    response = HttpResponse(png, content_type='image/png')
    return response


def log_out(request):
    user = request.session['current_user']
    curr = Account.objects.get(id=user)
    curr.waiting_for_game = False
    curr.save()
    request.session['current_user'] = 0
    return redirect('/login')

def benis(request):
    return render(request,'benis.html')

yahtzee_app/templates/benis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <title>Document</title>
</head>
<body>
    <h1 id="demo">
    </h1>
    <button type="button" onclick="loadDoc()">Get my CD collection</button>
    <script>
    function loadDoc() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
          if (this.readyState == 4 && this.status == 200) {
            console.log('aaa')
            document.getElementById("demo").innerHTML =
            this.responseText;
          }
        };
      }
    </script>
</body>
</html>

yahtzee_app/templates/game.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"> 
    <title>Yahtzee</title>
</head>

<body>
    <style>
        body {
            background-image: url("static/imgs/back.jpg");
            background-size: cover;
            color: #fff;
        }

        img {
            height: 50%;
            margin-right: 25px;
            margin-left: 25px;
        }

        .row {
            height: 200px;
            background: rgba(200, 0, 0, 0.6) !important;
        }

        .card {
            height: 200px;
            margin-top: -2px;
            background: transparent;
            padding-left: 90px;
        }

        .footer {
            margin-top: 600px;
            margin-bottom: -43px;
        }
        h2 {
            height: 63px;
            width: 150px;
            margin-top: -140px;
            margin-left: 77%;
            background: rgba(62, 60, 60, 0.4);
            padding-left: 15px;
        }
        .btn {
            margin-top: 145px;
            margin-right: 41px;
            margin-left: 39px;
        }
        .invade {
            margin-top: -216px;
        }
        .btn-large {
            margin-top: -130px;
            margin-left: 100px;
            background: rgba(18,59,147,0.3)
        }
        .btn-large:hover {
            background: rgb(18,59,147)
        }
    </style>
    <div class="row">
            <div class="col s10 l6 offset-l3 offset-m1 offset-s1">
            <div class="card valign-wrapper">
                <img src="{{num1}}" />
                <img src="{{num2}}" />
                <img src="{{num3}}" />
                <img src="{{num4}}" />
                <img src="{{num5}}" />
            </div>
            <div class="card valign-wrapper invade">
                <button id="dec1" class="btn grey">Keep</button>
                <button id="dec2" class="btn grey">Keep</button>
                <button id="dec3" class="btn grey">Keep</button>
                <button id="dec4" class="btn grey">Keep</button>
                <button id="dec5" class="btn grey">Keep</button>
            </div>
        </div>
    </div>
    <div class="row footer">
        <div class="col s10 l6 offset-l3 offset-m1 offset-s1">
            <div class="card valign-wrapper">
                <div class="menu">
                    {% for i in score %}
                        {% if i == 5 %}
                            <h2 style="color:black; background:yellow; height:60px; width:225px; margin-top:25px; margin-left:-10px">Yahtzee!</h2>
                        {% endif %}
                        {% if i == 4 %}
                            <h4 style="color:blue">Four of a kind</h4>
                        {% endif %}
                    {% endfor %}
                    {% if triple == 1 %}
                        <h4 style="color:green">Three of a kind</h4>
                    {% endif %}
                    {% if pair == 1 %}
                        <h4 style="color:purple">Pair</h4>
                    {% endif %}
                    {% if pair == 2 %}
                        <h4 style="color:purple">Two Pairs</h4>
                    {% endif %}
                    {% if full == True %}
                        <h4 style="color:turquoise">Full House</h4>
                    {% endif %}
                    {% if total == 0 %}
                        <h4 style="color:red; background:black;">None</h4>
                    {% endif %}
                </div>
            </div>
            <h2>{{total}}pts</h2>
        </div>
    </div>
    <a class="btn-large" href="/lobby_process">Back to Lobby</a>
    <script>
        $(document).ready(function(){

            $("#dec1").click(function(){
                if (document.getElementById("dec1").innerHTML != 'Roll')
                    {
                    document.getElementById("dec1").innerHTML = 'Roll'
                    }
                else
                    {
                    document.getElementById("dec1").innerHTML = 'Keep'
                    }
            })
            $("#dec2").click(function(){
                if (document.getElementById("dec2").innerHTML != 'Roll')
                    {
                    document.getElementById("dec2").innerHTML = 'Roll'
                    }
                else
                    {
                    document.getElementById("dec2").innerHTML = 'Keep'
                    }
            })
            $("#dec3").click(function(){
                if (document.getElementById("dec3").innerHTML != 'Roll')
                    {
                    document.getElementById("dec3").innerHTML = 'Roll'
                    }
                else
                    {
                    document.getElementById("dec3").innerHTML = 'Keep'
                    }
            })
            $("#dec4").click(function(){
                if (document.getElementById("dec4").innerHTML != 'Roll')
                    {
                    document.getElementById("dec4").innerHTML = 'Roll'
                    }
                else
                    {
                    document.getElementById("dec4").innerHTML = 'Keep'
                    }
            })
            $("#dec5").click(function(){
                if (document.getElementById("dec5").innerHTML != 'Roll')
                    {
                    document.getElementById("dec5").innerHTML = 'Roll'
                    }
                else
                    {
                    document.getElementById("dec5").innerHTML = 'Keep'
                    }
            })
        })
    </script>
</body>

</html>

yahtzee_app/templates/lobby.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        {% load static %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}"> 
        <title>Yahtzee</title>
    </head>
    <body>
        <style>
            body {
                background-image: url("static/imgs/back.jpg");
                background-size: cover;
                color: rgb(201, 201, 201);
            }
            .card-action {
                height: 100px;
            }
            .card {
                height: 100px;
                margin-top: 120px;
            }
            table {
                background: rgba(0, 100, 10, 0.5);
            }
            h1 {
                letter-spacing: 1px;
                line-height: 0px;
                margin-top: 33px;
                font-weight: 600;
                color: rgb(227, 227, 227);
            }
            td {
                font-size: 30px;
            }
            .logout {
                height: 35px;
                width: 100px;
                line-height: 32px;
                font-weight: 500;
                margin-top: -225px;
                margin-right: 50px;
                font-size: 20px;
                color: rgb(206, 176, 5);
                background: rgba(0, 0, 0, 0.3);
                border-radius: 30px;
            }
            .graph {
                height: 35px;
                width: 100px;
                line-height: 32px;
                font-weight: 500;
                margin-top: -180px;
                margin-right: 50px;
                font-size: 20px;
                color: rgb(5, 35, 206);
                background: rgba(0, 0, 0, 0.3);
                border-radius: 30px;
            }
            .logout:hover {
                background: rgb(0, 0, 0);
            }
            .graph:hover {
                background: rgb(0, 0, 0);
            }
            .valign-wrapper {
                margin-top: -90px;
                margin-left: 1350px;
            }
        </style>

        <div class="row">
            <div class="col s12 l8 offset-l2">
                <div class="card white center-align">
                    <div class="card-action red lighten-1 white-text">
                        <h1>Lobby</h1>
                        <div class="valign-wrapper">
                            <h4 id="count">5</h4>
                            <i class="material-icons prefix small">refresh</i>
                        </div>
                    </div>
                    <table class="centered highlight responsive-table">
                        <tbody>
                            {% for i in users %}
                                {% if i.waiting_for_game == True %}
                                <tr>
                                    <td>{{i.first_name}}</td>
                                    <td><a href="/game_process/{{i.id}}">Join</a></td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                            {% if noneq == True %}
                            <tr>
                                <td>No Games To Join</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <a class="logout right center-align" href="/log_out">Log Out</a>
        <a class="graph right center-align" href="/probability">Graph</a>

        <script>
            $(document).ready(function() {
                function refresh() {
                    location.reload();
                }
                setInterval(refresh, 5000);
                function count_down(){
                    x = document.getElementById("count").innerHTML
                    x = x - 1
                    document.getElementById("count").innerHTML = x
                    console.log('aaa')
                    
                }
                setInterval(count_down, 1000)
            });
        </script>
    </body>
</html>

yahtzee_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        {% load static %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}"> 
        <title>Yahtzee</title>
    </head>

    <body>
        <style>
            body {
                background-image: url("static/imgs/back.jpg");
                background-size: cover;
                color: #fff;
            }

            .card {
                margin-top: 200px;
            }

            .card {
                background: rgba(0, 0, 0, 0.6);
            }

            .login label {
                font-size: 16px;
                color: #ccc;
            }

            .login input {
                font-size: 22px;
                color: #fff;
            }

            .login button:hover {
                padding: 0px 50px;
            }

            button {
                margin-bottom: 20px;
            }

            a {
                color: lightskyblue;
                font-size: 20px;
            }

            .center {
                margin-bottom: -20px;
            }
            ul {
                margin-bottom: -31px;
                background: red;
                color: white;
                font-weight: 500;
                font-size: 30px;
            }
        </style>
        <div class="row login">
            <div class="col s12 l4 offset-l4">
                <div class="card">
                    <div class="card-action red lighten-1 white-text">
                        <h3>Login</h3>
                    </div>
                    <form action="login/process" method="POST">
                        {% csrf_token %}
                        <div class="card-content">
                            <div class="input-field">
                                <i class="material-icons prefix">email</i>
                                <input type="text" name="email" placeholder="Email" required />
                            </div>
                            <br />
                            <div class="input-field">
                                <i class="material-icons prefix">lock</i>
                                <input type="password" name="password" placeholder="Password" required />
                            </div>
                            <br />
                            <div class="center form-field center-align">
                                <button class="btn-large red">Login</button><br />
                                <a href="/register">Create Account</a>
                                {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                            <br />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>

yahtzee_app/templates/probability.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}"> 
        <title>Yahtzee</title>
    </head>
    <body>
        <style>
            body {
                background-image: url("static/imgs/back.jpg");
                background-size: cover;
                color: #fff;
            }
            h5,h6{
                color: black;
            }
            img {
	        display: inline-block;
            }
            /* .detail {
                display: inline-block;
            } */
            td {
            	padding: 10px;
            }
            .rank {
            	display: inline-block;
            	position: absolute;
            	bottom: 90px;
            	right: 500px;
            }
            .probability {
            	display: inline-block;
            	position: absolute;
            	bottom: 200px;
            	right: 180px;
            }
            .logout {
                height: 35px;
                width: 100px;
                line-height: 32px;
                font-weight: 500;
                margin-top: -145px;
                margin-right: 50px;
                font-size: 20px;
                color: rgb(206, 176, 5);
                background: rgba(0, 0, 0, 0.3);
                border-radius: 30px;
            }
            .logout:hover {
                background: rgb(0, 0, 0);
            }
            .back {
                height: 35px;
                width: 150px;
                line-height: 32px;
                font-weight: 500;
                margin-top: -100px;
                margin-right: 50px;
                font-size: 20px;
                color: rgb(5, 35, 206);
                background: rgba(0, 0, 0, 0.3);
                border-radius: 30px;
            }
            .back:hover {
                background: rgb(0, 0, 0);
            }

        </style>
        	<body>
                <h3>{{user.first_name}}'s result:</h3>
                <div class="detail">
                    <h5>Max score:{{request.session.max}}</h5>
                    <h5>Average score:{{request.session.ave}}</h5>
                </div>
                <img src="{% url 'yahtzee_app:img_plot' %}" alt="" />
        
                <div class="rank">
                    <h5>Ranking:</h5>
                    <table>
                        <tr>
                            <th></th>
                            <th><h6>Today's Ranking</h6></th>
                            <th><h6>Month's Ranking</h6></th>
                        </tr>
                        {% for i in arr %}
                        <tr>
                            <td>{{ i }}</td>
                            <td>User name{{i}}: {% widthratio 400 i 1%}pt</td>
                            <td>User name{{i}}: {% widthratio 4500 i 1%}pt</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="probability">
                    <h5>First roll probability</h5>
                    <table>
                        <tr>
                            <th><h6>Category</h6></th>
                            <th><h6>Probability(%)</h6></th>
                        </tr>
                        <tr>
                            <td>3 of a Kind</td>
                            <td>19.29%</td>
                        </tr>
                        <tr>
                            <td>4 of a Kind</td>
                            <td>1.93%</td>
                        </tr>
                        <tr>
                            <td>Big Straights</td>
                            <td>3.11%</td>
                        </tr>
                        <tr>
                            <td>Small Straights</td>
                            <td>21.60%</td>
                        </tr>
                        <tr>
                            <td>Full house</td>
                            <td>3.86%</td>
                        </tr>
                        <tr>
                            <td>Yahtzee</td>
                            <td>0.08%</td>
                        </tr>
                    </table>
                </div>
                <a class="logout right center-align" href="/log_out">Log Out</a>
                <a class="back right center-align" href="/lobby">Back to Lobby</a>
            </body>
        </html>